# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: empty.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='empty.proto',
  package='carrier',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0b\x65mpty.proto\x12\x07\x63\x61rrier\"\x0f\n\rEmptyResponseb\x06proto3')
)




_EMPTYRESPONSE = _descriptor.Descriptor(
  name='EmptyResponse',
  full_name='carrier.EmptyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=39,
)

DESCRIPTOR.message_types_by_name['EmptyResponse'] = _EMPTYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EmptyResponse = _reflection.GeneratedProtocolMessageType('EmptyResponse', (_message.Message,), dict(
  DESCRIPTOR = _EMPTYRESPONSE,
  __module__ = 'empty_pb2'
  # @@protoc_insertion_point(class_scope:carrier.EmptyResponse)
  ))
_sym_db.RegisterMessage(EmptyResponse)


# @@protoc_insertion_point(module_scope)
