# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import carrier_pb2 as carrier__pb2


class CarrierServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateCarrier = channel.unary_unary(
        '/carrier.CarrierService/CreateCarrier',
        request_serializer=carrier__pb2.CreateCarrierRequest.SerializeToString,
        response_deserializer=carrier__pb2.Carrier.FromString,
        )


class CarrierServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateCarrier(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CarrierServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateCarrier': grpc.unary_unary_rpc_method_handler(
          servicer.CreateCarrier,
          request_deserializer=carrier__pb2.CreateCarrierRequest.FromString,
          response_serializer=carrier__pb2.Carrier.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'carrier.CarrierService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
